# syntax=docker/dockerfile:1
# test
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY ./backend/requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/